### PR TITLE
Add a flake for agda2hs

### PR DESCRIPTION
**Pull request by liesnikov**
I've been using nix for CI and to build agda-core locally for https://github.com/jespercockx/agda-core and I had to write a derivation for agda2hs anyway, so I figured I'll push it upstream.

In the flake there are
* agda2hs the executable (`agda2hs`)
* agda2hs the agda library (`agda2hs-lib`)
* a derivation to build agda2hs with agda libraries (`withPackages`)

I also added a CI builder for the nix derivations.

There's some weird behavior when we compile with ghc 9.4 using nix -- an instance of MonadError can't be found.
For this to happen one must do jailbreak, because otherwise aeson and transformers don't satisfy version requirements.

```
agda2hs> Error: Setup: Encountered missing or private dependencies:
agda2hs> aeson >=2.2 && <2.3, transformers >=0.6 && <0.7
```

<details> 
  <summary>Build log for ghc 9.4 with a jailbroken package  </summary>

```
agda2hs> [ 4 of 23] Compiling Agda2Hs.Pragma   ( src/Agda2Hs/Pragma.hs, dist/build/agda2hs/agda2hs-tmp/Agda2Hs/Pragma.o )
agda2hs> src/Agda2Hs/Pragma.hs:79:45: error:
agda2hs>     • No instance for (Control.Monad.Error.Class.MonadError
agda2hs>                          TCErr
agda2hs>                          (Control.Monad.Trans.RWS.CPS.RWST
agda2hs>                             CompileEnv CompileOutput CompileState TCM))
agda2hs>         arising from a use of ‘genericError’
agda2hs>     • In the second argument of ‘($)’, namely ‘genericError msg’
agda2hs>       In the expression:
agda2hs>         setCurrentRange (srcLocToRange loc) $ genericError msg
agda2hs>       In a case alternative:
agda2hs>           Hs.ParseFailed loc msg
agda2hs>             -> setCurrentRange (srcLocToRange loc) $ genericError msg
agda2hs>    |
agda2hs> 79 |       setCurrentRange (srcLocToRange loc) $ genericError msg
agda2hs>    |                                             ^^^^^^^^^^^^
agda2hs> [ 5 of 23] Compiling AgdaInternals    ( src/AgdaInternals.hs, dist/build/agda2hs/agda2hs-tmp/AgdaInternals.o )
agda2hs> [ 6 of 23] Compiling Agda2Hs.AgdaUtils ( src/Agda2Hs/AgdaUtils.hs, dist/build/agda2hs/agda2hs-tmp/Agda2Hs/AgdaUtils.o )
agda2hs> [15 of 23] Compiling Agda2Hs.Compile.Function[boot] ( src/Agda2Hs/Compile/Function.hs-boot, dist/build/agda2hs/agda2hs-tmp/Agda2Hs/Compile/Function.o-boot )
agda2hs> [22 of 23] Compiling Paths_agda2hs    ( dist/build/agda2hs/autogen/Paths_agda2hs.hs, dist/build/agda2hs/agda2hs-tmp/Paths_agda2hs.o )
error: builder for '/nix/store/s9jv2y4ympsqlc4jrk60lhjxfv4rv6jl-agda2hs-1.3.drv' failed with exit code 1;
       last 10 log lines:
       >       In a case alternative:
       >           Hs.ParseFailed loc msg
       >             -> setCurrentRange (srcLocToRange loc) $ genericError msg
       >    |
       > 79 |       setCurrentRange (srcLocToRange loc) $ genericError msg
       >    |                                             ^^^^^^^^^^^^
       > [ 5 of 23] Compiling AgdaInternals    ( src/AgdaInternals.hs, dist/build/agda2hs/agda2hs-tmp/AgdaInternals.o )
       > [ 6 of 23] Compiling Agda2Hs.AgdaUtils ( src/Agda2Hs/AgdaUtils.hs, dist/build/agda2hs/agda2hs-tmp/Agda2Hs/AgdaUtils.o )
       > [15 of 23] Compiling Agda2Hs.Compile.Function[boot] ( src/Agda2Hs/Compile/Function.hs-boot, dist/build/agda2hs/agda2hs-tmp/Agda2Hs/Compile/Function.o-boot )
       > [22 of 23] Compiling Paths_agda2hs    ( dist/build/agda2hs/autogen/Paths_agda2hs.hs, dist/build/agda2hs/agda2hs-tmp/Paths_agda2hs.o )
```

</details>

With ghc 9.6 it builds without (almost) hiccups (current [default](https://github.com/NixOS/nixpkgs/blob/cb11f8589769078fa154fb57ed8edd185281f1db/pkgs/top-level/all-packages.nix#L16069) in nixpkgs, as of cb11f8). 
I still decided to jailbreak because the default aeson version is slightly outdated - not sure why - and overriding it to the aeson 2.2 triggers a recompilation of a lot of dependencies.

There's also a devshell derivation that should be a superset of the current shell.nix, but I haven't tested it too much.

Examples of this flake's usage: https://github.com/liesnikov/scope/blob/master/flake.nix and https://github.com/liesnikov/agda-core/blob/flakes/flake.nix

~~Finally the dependency on `mkAgdaDerivation` is due to the fact that upstream agda derivation needs an Everything file which agda2hs doesn't have. I might file a PR to nixpkgs to fix it later but for now it lives in a separate repo.~~
edit: borrowed a trick from nixpkgs to remove it

### CODE REVIEW

**Comment by liesnikov** [comment]
In principle it's also possible to setup cachix for agda2hs builds to be cached across different runners/users, but that's a separate story.
