### ISSUE TITLE
Support building with GHC 9.10 (base-4.20)

### ISSUE THREAD

**Issue by cho-m** [agda/agda2hs#347]
Lifting the upper bound of `base` does allow build to succeed:

https://github.com/agda/agda2hs/blob/7753783a316de2db07da627f47058ed83bbc9876/agda2hs.cabal#L63

---

Opened this as working on updating to GHC 9.10.1 in Homebrew (https://github.com/Homebrew/homebrew-core/pull/178590) and noticed the Homebrew `agda` formula failed to build with GHC 9.10.1 when building `agda2hs`.

**Comment by jespercockx** [comment]
It seems we should get rid of `head` from our codebase:
```haskell
src/Agda2Hs/Compile.hs:132:139: error: [GHC-63394] [-Wx-partial, -Werror=x-partial]
    In the use of ‘head’
    (imported from Prelude, but defined in GHC.Internal.List):
    "This is a partial function, it throws an error on empty lists. Use pattern matching, 'Data.List.uncons' or 'Data.Maybe.listToMaybe' instead. Consider refactoring to use "Data.List.NonEmpty"."
    |
132 |         genericDocError =<< vcat (map (\x -> text $ "Cannot generate multiple constructors with the same identifier: " <> Hs.prettyPrint (head x)) duplicateCons)
    |                                                                                                                                           ^^^^
```
